Hitting backspace on a list item with nothing in it should delete the…
mwildehahn/lexical-ios pull request #5
Opened 2024-11-26 17:59 UTC by nemanja-kovacevic

… bullet/number/checkbox and leave you on an empty line (instead of taking you up a line)

2024-11-26 22:09 UTC, mwildehahn requested changes

2024-11-26 22:09 UTC, mwildehahn commented on Lexical/Core/Selection/RangeSelection.swift
> +          if  selectedNode.isToBeReplacedWithEmptyParagraphOnDeletion() && selectedNode.isParentOf(anchorNode) {
I think instead of this we can just override the `remove` method of the list: https://github.com/mwildehahn/lexical-ios/blob/85a156b6bd7fef9ab25a1118218bd60b370311ed/Lexical/Core/Nodes/Node.swift#L525-L528

2024-11-26 22:25 UTC, nemanja-kovacevic commented on Lexical/Core/Selection/RangeSelection.swift
> +          if  selectedNode.isToBeReplacedWithEmptyParagraphOnDeletion() && selectedNode.isParentOf(anchorNode) {
okay, I'll give it a go tomorrow.

2024-11-28 13:46 UTC, nemanja-kovacevic commented on Lexical/Core/Selection/RangeSelection.swift
> +          if  selectedNode.isToBeReplacedWithEmptyParagraphOnDeletion() && selectedNode.isParentOf(anchorNode) {
you were right, it's far cleaner your way, so I'll just close this PR.

2024-11-28 13:47 UTC, closed without merging